version: 1.0.0.{build}

platform: x64

environment:
  ASEPRITE_VERSION: v1.2.6

install:
  - git clone -b %ASEPRITE_VERSION% --single-branch https://github.com/aseprite/aseprite.git C:\aseprite
  - cd C:\aseprite

build: off
