version: 1.0.0.{build}

platform: x64

environment:
  ASEPRITE_VERSION: v1.2.6

install:
  - git clone -b %ASEPRITE_VERSION% --single-branch https://github.com/aseprite/aseprite.git C:\aseprite
  - mkdir -p C:\deps\depot_tools
  - curl -fsSL https://storage.googleapis.com/chrome-infra/depot_tools.zip -o C:\deps\depot_tools\depot_tools.zip
  - cd C:\deps\depot_tools
  - 7z x depot_tools.zip
  - ls

build: off
