version: 1.0.0.{build}

image: Visual Studio 2017

platform: x64

environment:
  ASEPRITE_VERSION: v1.2.6

install:
  - git clone -b %ASEPRITE_VERSION% --single-branch https://github.com/aseprite/aseprite.git C:\aseprite
  - mkdir -p C:\deps\depot_tools
  - curl -fsSL https://storage.googleapis.com/chrome-infra/depot_tools.zip -o C:\deps\depot_tools\depot_tools.zip
  - cd C:\deps\depot_tools
  - 7z x depot_tools.zip
  - rm depot_tools.zip
  - ls "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
  - set PATH=C:\deps\depot_tools;%PATH%
  - gclient sync

build: off
